import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import home from "@/app/Component/page"
import Navbar from "@/app/Components/Navbar";
//import Automate from "@/app/Components/Automation"
import Footer from "@/app/Components/Footer_session/Footer"
import Location from "@/app/Components/Footer_session/Location"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        {children}
        <Location />
        <Footer />
      </body>
    </html>
  );
}
